# Generated by Django 3.2 on 2021-04-30 07:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0002_auto_20210430_0726'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exam',
            new_name='Form',
        ),
    ]
