# Generated by Django 3.2 on 2021-04-30 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0004_auto_20210430_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('is_score', models.BooleanField(default=False)),
                ('view_score', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optn', models.CharField(max_length=1000)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=1000)),
                ('req', models.BooleanField(default=False)),
                ('key', models.CharField(max_length=1000, null=True)),
                ('q_type', models.CharField(max_length=30)),
                ('points', models.IntegerField(null=True)),
                ('options', models.ManyToManyField(related_name='options', to='forms.Options')),
            ],
        ),
        migrations.RemoveField(
            model_name='form',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='form',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='choices',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(related_name='questions', to='forms.Question'),
        ),
        migrations.AddField(
            model_name='ans',
            name='corresponds',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corresponds', to='forms.question'),
        ),
    ]
