# Generated by Django 3.2 on 2021-04-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20210430_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='uuid',
            field=models.CharField(max_length=30),
        ),
    ]
