# Generated by Django 3.2 on 2021-05-01 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_alter_exam_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='is_score',
            new_name='is_publish',
        ),
    ]
