# Generated by Django 3.2 on 2021-05-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='responder_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
