# Generated by Django 3.1.7 on 2022-09-25 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_auto_20220924_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='submittedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
