# Generated by Django 3.2 on 2021-04-29 02:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0006_alter_profile_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pincode',
            field=models.CharField(max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
