# Generated by Django 3.1.7 on 2022-09-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0008_auto_20220924_1744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
